(lang dune 3.16)

(name protocaml)

(generate_opam_files true)

(source
 (github username/reponame))

(authors "Vedant Nevetia")

(maintainers "Vedant Nevetia")

(license LICENSE)

(documentation https://url/to/documentation)

(package
 (name protocaml)
 (synopsis "OCaml Protobuf Parser")
 (description "OCaml Protobuf Parser")
 (depends ocaml dune)
 (tags
  (topics "to describe" your project)))

; See the complete stanza docs at https://dune.readthedocs.io/en/stable/reference/dune-project/index.html
